### ISSUE TITLE
Support for other numeric literals

### ISSUE THREAD

**Issue by mathiasgredal** [jakob753951/ASMJ-VOLE-transpiler#1]
Right now, the assembler only supports hexadecimal notation as a numeric literal, while other assemblers support a whole range of literal types. I propose we adopt the arm specification for numeric literal notation: https://developer.arm.com/documentation/dui0473/c/symbols--literals--expressions--and-operators/numeric-literals

While doing this we should of course check that we don't overflow the maximum value of 256.

(I would add a feature request label, but none seem to exist...)

**Comment by mathiasgredal** [comment]
Perhaps using the arm spec, is not optimal since we break backwards compatibility and it has no support for floating point numbers. It also doesn't support scientific notation.

**Comment by jakob753951** [comment]
Should be added with commit 01d8a5ddd15a017102ffcaebe22bc313bed59462
Different bases are used with the prefixes
0x for hex
0d for decimal
0o for octal
0b for binary

No prefix is parsed as hex, so we don't break backwards compability
